// Optional real-browser smoke test, using Chrome's DevTools protocol (no test dependencies).
import { spawn } from 'node:child_process';
import { mkdir, writeFile, readdir, readFile, rm } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import { STLExporter } from 'three/addons/exporters/STLExporter.js';
import { STLLoader } from 'three/addons/loaders/STLLoader.js';
import { mergeVertices } from 'three/addons/utils/BufferGeometryUtils.js';
import { validateSolid } from '../src/meshUtils.js';
import { archive3MF, modelXML, tetraMesh, wideOBJ } from './import-fixtures.js';

const artifacts = path.resolve('artifacts');
await mkdir(artifacts, { recursive: true });
const chrome = spawn(process.env.CHROME_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', [
  '--headless=new', '--no-first-run', '--no-default-browser-check', '--enable-unsafe-swiftshader',
  '--remote-debugging-port=9223', `--user-data-dir=${path.resolve('.browser-profile')}`, 'about:blank'
], { windowsHide: true, stdio: ['ignore', 'ignore', 'pipe'] });
let chromeLog = '';
chrome.stderr.on('data', chunk => { chromeLog += chunk.toString(); });
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
let socket;
try {
  let targets;
  for (let i = 0; i < 100; i++) { try { targets = await (await fetch('http://127.0.0.1:9223/json')).json(); break; } catch { await sleep(200); } }
  assert.ok(targets, 'Chrome remote debugging started');
  socket = new WebSocket(targets.find(t => t.type === 'page').webSocketDebuggerUrl);
  await new Promise(resolve => socket.addEventListener('open', resolve, { once: true }));
  let sequence = 0; const waiting = new Map(), errors = [];
  socket.addEventListener('message', event => {
    const result = JSON.parse(event.data);
    if (result.id) { const pending = waiting.get(result.id); waiting.delete(result.id); if (result.error) pending?.reject(new Error(result.error.message)); else pending?.resolve(result.result); }
    if (result.method === 'Runtime.exceptionThrown') errors.push(result.params.exceptionDetails.text);
  });
  const send = (method, params = {}) => new Promise((resolve, reject) => { const id = ++sequence; const timeout = setTimeout(() => reject(new Error(`CDP timeout: ${method}; ${chromeLog}`)), 20000); waiting.set(id, { resolve: value => { clearTimeout(timeout); resolve(value); }, reject: error => { clearTimeout(timeout); reject(error); } }); socket.send(JSON.stringify({ id, method, params })); });
  const evaluate = async expression => { const r = await send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw new Error(JSON.stringify(r.exceptionDetails)); return r.result.value; };
  const waitFor = async expression => { for (let i = 0; i < 300; i++) { if (await evaluate(expression)) return; await sleep(100); } throw new Error(`Timed out: ${expression}; status ${await evaluate('document.body.innerText')}`); };
  await send('Runtime.enable'); await send('Page.enable');
  await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
  await send('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: artifacts });
  await send('Page.navigate', { url: process.env.APP_URL || 'http://127.0.0.1:5173' });
  await waitFor('document.querySelector("#export") && !document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#status").textContent'), /Watertight/);
  await sleep(800);
  const shot = await send('Page.captureScreenshot', { format: 'png' }); await writeFile(path.join(artifacts, 'desktop.png'), Buffer.from(shot.data, 'base64'));
  await evaluate('document.querySelector("#targetSize").value=130.5; document.querySelector("#targetSize").dispatchEvent(new Event("input"));');
  await waitFor('!document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#source-details").textContent'), /60.0 × 51.0 × 130.5/);
  await evaluate('document.querySelector("#targetSize").value=0; document.querySelector("#targetSize").dispatchEvent(new Event("input"));');
  await waitFor('document.querySelector("#status").className === "error"');
  assert.equal(await evaluate('document.querySelector("#export").disabled'), true);
  await evaluate('document.querySelector("#reset-size").click()');
  await waitFor('!document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#source-details").textContent'), /40.0 × 34.0 × 87.0/);
  await evaluate('document.querySelector("#eyes").click()');
  assert.equal(await evaluate('document.querySelector("#hollow").checked'), true);
  assert.equal(await evaluate('document.querySelector("#export").disabled'), true);
  await waitFor('!document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#output-note").textContent'), /2 mm walls.*open underside.*eye openings/);
  await evaluate('document.querySelector("#hollow").scrollIntoView({block:"start"})');
  await sleep(300);
  const hollowShot = await send('Page.captureScreenshot', { format: 'png' }); await writeFile(path.join(artifacts, 'hollow-eyes.png'), Buffer.from(hollowShot.data, 'base64'));
  await rm(path.join(artifacts, 'rabbit_ghost.stl'), { force: true });
  await evaluate('document.querySelector("#export").click()');
  for (let i = 0; i < 50 && !(await readdir(artifacts)).includes('rabbit_ghost.stl'); i++) await sleep(100);
  const downloadedHollow = await readFile(path.join(artifacts, 'rabbit_ghost.stl'));
  const hollowGeometry = new STLLoader().parse(downloadedHollow.buffer.slice(downloadedHollow.byteOffset, downloadedHollow.byteOffset + downloadedHollow.byteLength));
  hollowGeometry.deleteAttribute('normal');
  assert.equal(validateSolid(mergeVertices(hollowGeometry, 1e-6)).watertight, true);
  await evaluate('document.querySelector("#eyeShape").value="round"; document.querySelector("#eyeShape").dispatchEvent(new Event("change"));');
  await waitFor('!document.querySelector("#export").disabled');
  assert.equal(await evaluate('document.querySelector("#eyeHeight-row").hidden'), true);
  await evaluate('document.querySelector("#openBottom").click(); document.querySelector("#wallThickness").value=2.5; document.querySelector("#wallThickness").dispatchEvent(new Event("input"));');
  await waitFor('!document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#output-note").textContent'), /2.5 mm walls.*closed floor/);
  await evaluate('document.querySelector("#eyeSpacing").value=1; document.querySelector("#eyeSpacing").dispatchEvent(new Event("input"));');
  await waitFor('!document.querySelector("#notice").hidden');
  assert.match(await evaluate('document.querySelector("#notice").textContent'), /spacing/);
  assert.equal(await evaluate('document.querySelector("#export").disabled'), true);
  await evaluate('document.querySelector("#hollow").click()');
  await waitFor('!document.querySelector("#export").disabled');
  assert.equal(await evaluate('document.querySelector("#eyes").checked'), false);
  await evaluate('document.querySelector("#eyes").click(); document.querySelector("#clickEyes").click(); document.querySelector("#eyeShape").value="oval"; document.querySelector("#eyeShape").dispatchEvent(new Event("change")); document.querySelector("#eyeWidth").value=3; document.querySelector("#eyeWidth").dispatchEvent(new Event("input")); document.querySelector("#eyeHeight").value=5; document.querySelector("#eyeHeight").dispatchEvent(new Event("input"));');
  await waitFor('!document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#placed-eye-count").textContent'), /^0 eyes/);
  const clickScene = async (x, y) => {
    await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x, y });
    await send('Input.dispatchMouseEvent', { type: 'mousePressed', x, y, button: 'left', clickCount: 1 });
    await send('Input.dispatchMouseEvent', { type: 'mouseReleased', x, y, button: 'left', clickCount: 1 });
  };
  await clickScene(400, 300); // Empty space must not add anything.
  assert.match(await evaluate('document.querySelector("#placed-eye-count").textContent'), /^0 eyes/);
  await clickScene(850, 605);
  await waitFor('document.querySelector("#placed-eye-list").children.length === 1 && !document.querySelector("#export").disabled');
  await evaluate('document.querySelector("#eyeShape").value="round"; document.querySelector("#eyeShape").dispatchEvent(new Event("change")); document.querySelector("#eyeWidth").value=4; document.querySelector("#eyeWidth").dispatchEvent(new Event("input"));');
  assert.equal(await evaluate('document.querySelector("#export").disabled'), false, 'Brush settings affect only future placements');
  await clickScene(913, 650);
  await waitFor('document.querySelector("#placed-eye-list").children.length === 2 && !document.querySelector("#export").disabled');
  await clickScene(834, 719);
  await waitFor('document.querySelector("#placed-eye-list").children.length === 3 && !document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#placed-eye-list").textContent'), /Oval · 3 × 5 mm.*Round · 4 × 4 mm/);
  await evaluate('document.querySelector("#clickEyes").scrollIntoView({block:"start"})');
  const clickShot = await send('Page.captureScreenshot', { format: 'png' }); await writeFile(path.join(artifacts, 'click-eyes.png'), Buffer.from(clickShot.data, 'base64'));
  await clickScene(850, 605); // An existing opening must not target the inner rear wall.
  assert.equal(await evaluate('document.querySelector("#placed-eye-list").children.length'), 3);
  await send('Input.dispatchMouseEvent', { type: 'mousePressed', x: 870, y: 600, button: 'left', clickCount: 1 });
  await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: 950, y: 620, buttons: 1 });
  await send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: 950, y: 620, button: 'left', clickCount: 1 });
  assert.equal(await evaluate('document.querySelector("#placed-eye-list").children.length'), 3, 'Orbit drag does not place an eye');
  await rm(path.join(artifacts, 'rabbit_ghost.stl'), { force: true });
  await evaluate('document.querySelector("#export").click()');
  for (let i = 0; i < 50 && !(await readdir(artifacts)).includes('rabbit_ghost.stl'); i++) await sleep(100);
  const clickedSTL = await readFile(path.join(artifacts, 'rabbit_ghost.stl'));
  const clickedGeometry = new STLLoader().parse(clickedSTL.buffer.slice(clickedSTL.byteOffset, clickedSTL.byteOffset + clickedSTL.byteLength));
  clickedGeometry.deleteAttribute('normal'); validateSolid(mergeVertices(clickedGeometry, 1e-6));
  await evaluate('document.querySelector("#eyeSpacing").value=13; document.querySelector("#clickEyes").click()');
  await waitFor('!document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#output-note").textContent'), /eye openings \(2\)/);
  await evaluate('document.querySelector("#clickEyes").click()');
  await waitFor('!document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#output-note").textContent'), /eye openings \(3\)/);
  await evaluate('document.querySelector("#undo-eye").click()');
  await waitFor('document.querySelector("#placed-eye-list").children.length === 2 && !document.querySelector("#export").disabled');
  await evaluate('document.querySelector("#placed-eye-list button").click()');
  await waitFor('document.querySelector("#placed-eye-list").children.length === 1 && !document.querySelector("#export").disabled');
  await evaluate('document.querySelector("#clear-eyes").click()');
  await waitFor('document.querySelector("#placed-eye-list").children.length === 0 && !document.querySelector("#export").disabled');
  await evaluate('document.querySelector("#hollow").click(); document.querySelector("#fit").click()');
  await waitFor('!document.querySelector("#export").disabled');
  await evaluate('document.querySelector(".sidebar").scrollTop=0');
  await evaluate('document.querySelector("#foldCount").value = 12; document.querySelector("#foldCount").dispatchEvent(new Event("input"));');
  assert.equal(await evaluate('document.querySelector("#export").disabled'), true);
  await waitFor('!document.querySelector("#export").disabled');
  assert.equal(await evaluate('document.querySelector("#foldCount-value").textContent'), '12');
  await evaluate('document.querySelector("[data-mode=source]").click(); document.querySelector("#rotate-x").value = 90; document.querySelector("#rotate-x").dispatchEvent(new Event("input"));');
  await waitFor('!document.querySelector("#export").disabled');
  assert.equal(await evaluate('document.querySelector("[data-mode=source]").getAttribute("aria-pressed")'), 'true');
  await evaluate('document.querySelector("#reset").click(); document.querySelector("[data-mode=ghost]").click();');
  await waitFor('!document.querySelector("#export").disabled');
  const source = new THREE.BoxGeometry(25, 30, 65).translate(200, -100, 100);
  const stl = new STLExporter().parse(new THREE.Mesh(source), { binary: true });
  const fixture = path.join(artifacts, 'test-figurine.stl'); await writeFile(fixture, Buffer.from(stl.buffer));
  const doc = await send('DOM.getDocument'); const node = await send('DOM.querySelector', { nodeId: doc.root.nodeId, selector: '#file' });
  await send('DOM.setFileInputFiles', { nodeId: node.nodeId, files: [fixture] });
  await waitFor('document.querySelector("#filename").textContent === "test-figurine.stl" && !document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#source-details").textContent'), /25.0 × 30.0 × 65.0/);
  await evaluate('document.querySelector("#export").click()');
  let downloaded = false;
  for (let i = 0; i < 30; i++) { if ((await readdir(artifacts)).includes('test-figurine_ghost.stl')) { downloaded = true; break; } await sleep(100); }
  assert.ok(downloaded, 'STL download created');
  await writeFile(path.join(artifacts, 'wide.obj'), wideOBJ);
  await send('DOM.setFileInputFiles', { nodeId: node.nodeId, files: [path.join(artifacts, 'wide.obj')] });
  await waitFor('document.querySelector("#filename").textContent === "wide.obj" && !document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#source-details").textContent'), /100.0 × 20.0 × 10.0/);
  await evaluate('document.querySelector("#targetSize").value=50; document.querySelector("#targetSize").dispatchEvent(new Event("input"));');
  await waitFor('!document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#source-details").textContent'), /500.0 × 100.0 × 50.0/);
  await evaluate('document.querySelector("#rotate-x").value=90; document.querySelector("#rotate-x").dispatchEvent(new Event("input"));');
  await waitFor('!document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#source-details").textContent'), /250.0 × 25.0 × 50.0/);
  const model3MF = archive3MF(modelXML(`<object id="1">${tetraMesh}</object>`, '<item objectid="1"/>', 'centimeter'));
  await writeFile(path.join(artifacts, 'test-3mf.3mf'), Buffer.from(model3MF));
  await send('DOM.setFileInputFiles', { nodeId: node.nodeId, files: [path.join(artifacts, 'test-3mf.3mf')] });
  await waitFor('document.querySelector("#filename").textContent === "test-3mf.3mf" && !document.querySelector("#export").disabled');
  assert.match(await evaluate('document.querySelector("#source-details").textContent'), /10.0 × 20.0 × 30.0/);
  assert.equal(await evaluate('document.querySelector("#targetSize").value'), '');
  await rm(path.join(artifacts, 'test-3mf_ghost.stl'), { force: true });
  await evaluate('document.querySelector("#export").click()');
  for (let i = 0; i < 50 && !(await readdir(artifacts)).includes('test-3mf_ghost.stl'); i++) await sleep(100);
  assert.ok((await readdir(artifacts)).includes('test-3mf_ghost.stl'), '3MF import exports STL with a clean filename');
  await writeFile(path.join(artifacts, 'broken.3mf'), 'invalid zip');
  await send('DOM.setFileInputFiles', { nodeId: node.nodeId, files: [path.join(artifacts, 'broken.3mf')] });
  await waitFor('!document.querySelector("#notice").hidden');
  assert.match(await evaluate('document.querySelector("#notice").textContent'), /3MF/);
  assert.equal(await evaluate('document.querySelector("#export").disabled'), true);
  await writeFile(path.join(artifacts, 'bad.stl'), 'not an STL');
  await send('DOM.setFileInputFiles', { nodeId: node.nodeId, files: [path.join(artifacts, 'bad.stl')] });
  await waitFor('!document.querySelector("#notice").hidden');
  assert.equal(await evaluate('document.querySelector("#export").disabled'), true);
  await evaluate('document.querySelector("#demo").click()');
  await waitFor('!document.querySelector("#export").disabled');
  await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await sleep(400);
  assert.equal(await evaluate('document.documentElement.scrollWidth <= window.innerWidth'), true);
  const mobile = await send('Page.captureScreenshot', { format: 'png' }); await writeFile(path.join(artifacts, 'mobile.png'), Buffer.from(mobile.data, 'base64'));
  assert.deepEqual(errors, [], 'No uncaught browser exceptions');
  console.log('Browser checks passed: click placement, three independent eyes, orbit/miss/opening filtering, per-eye sizes, paired mode preservation, undo/remove/clear, clicked STL round trip, hollowing, round/oval eyes, wall thickness, open/closed floor, hollow STL round trip, invalid eye settings, demo, live updates, orientation, preview modes, upload, export, invalid STL recovery, mobile layout.');
  await send('Browser.close');
} finally { socket?.close(); chrome.kill(); }
